<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>bench</AssemblyName>
    <RootNamespace>bench</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Whisper.net" Version="1.7.4" />
    <PackageReference Include="Whisper.net.Runtime" Version="1.7.4" />
    <PackageReference Include="Whisper.net.Runtime.Cuda" Version="1.7.4" />
    <PackageReference Include="Whisper.net.Runtime.Vulkan" Version="1.7.4" />
  </ItemGroup>
</Project>
